version: '3.4'

services:
  catalog-api:
    build: ./Catalog/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5154:80"
    networks:
      - internal
  basket-api:
    build: ./Basket/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5289:80"
    networks:
      - internal
  getway:
    build: ./Getway/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      #- ConnectionString=YOUR_VALUE
    ports:
      - "5555:80"
    networks:
      - internal
    depends_on:
      - catalog-api
      - basket-api
networks:
  internal:
    driver: bridge